### PR TITLE
fix: wrong namespace removal on nested repeated refs

### LINKED ISSUE #206: SchemaParseException: Undefined name | namespace removal in nested references
When generating a schema, namespaces should be retained in nested structures that belong to a different namespace. The namespace should only be removed when the nested structure shares the same namespace as its parent. However, whenever it's a repeated reference the current output incorrectly removes namespaces even when the nested structure belongs to a different namespace, leading to undefined name.

Debugging this, I found out that the issue happens because `AvroSchemaParser` is removing the namespace from the references when it is reused throughout the schema and its included on a nested structure that share the same namespace.

Here's a reproducible example:
```
{
  "type": "record",
  "name": "MainRecord",
  "namespace": "com.example",
  "fields": [
    {
      "name": "foo",
      "type": "com.example.one.NestedOne"
    },
    {
      "name": "bar",
      "type": "com.common.example.NestedTwo"
    }
  ]
}
```
```
{
  "type": "record",
  "name": "NestedOne",
  "namespace": "com.example.one",
  "fields": [
    {
      "name": "foo",
      "type": "string"
    },
    {
      "name": "bar",
      "type": "com.common.example.Common"
    }
  ]
}
```
```
{
  "type": "record",
  "name": "NestedTwo",
  "namespace": "com.common.example",
  "fields": [
    {
      "name": "foo",
      "type": "string"
    },
    {
      "name": "bar",
      "type": "com.common.example.Common"
    }
  ]
}
```
```
{
  "type": "record",
  "name": "Common",
  "namespace": "com.common.example",
  "fields": [
    {
      "name": "foo",
      "type": "string"
    }
  ]
}
```

**Expected:**
```
{
    "name": "MainRecord",
    "namespace": "com.example",
    "type": "record",
    "fields":
    [
        {
            "name": "foo",
            "type":
            {
                "name": "NestedOne",
                "namespace": "com.example.one",
                "type": "record",
                "fields":
                [
                    {
                        "name": "foo",
                        "type": "string"
                    },
                    {
                        "name": "bar",
                        "type":
                        {
                            "name": "Common",
                            "namespace": "com.common.example",
                            "type": "record",
                            "fields":
                            [
                                {
                                    "name": "foo",
                                    "type": "string"
                                }
                            ]
                        }
                    }
                ]
            }
        },
        {
            "name": "bar",
            "type":
            {
                "name": "NestedTwo",
                "namespace": "com.common.example",
                "type": "record",
                "fields":
                [
                    {
                        "name": "foo",
                        "type": "string"
                    },
                    {
                        "name": "bar",
                        "type": "com.common.example.Common"
                    }
                ]
            }
        }
    ]
}
```

**Current output:**
```
{
    "name": "MainRecord",
    "namespace": "com.example",
    "type": "record",
    "fields":
    [
        {
            "name": "foo",
            "type":
            {
                "name": "NestedOne",
                "namespace": "com.example.one",
                "type": "record",
                "fields":
                [
                    {
                        "name": "foo",
                        "type": "string"
                    },
                    {
                        "name": "bar",
                        "type":
                        {
                            "name": "Common", <-- namespace was removed on NestedTwo
                            "type": "record",
                            "fields":
                            [
                                {
                                    "name": "foo",
                                    "type": "string"
                                }
                            ]
                        }
                    }
                ]
            }
        },
        {
            "name": "bar",
            "type":
            {
                "name": "NestedTwo",
                "namespace": "com.common.example",
                "type": "record",
                "fields":
                [
                    {
                        "name": "foo",
                        "type": "string"
                    },
                    {
                        "name": "bar",
                        "type": "com.common.example.Common" <-- triggers removal of namespace 
                    }
                ]
            }
        }
    ]
}
```

Thx!

### PR DESCRIPTION
**Pull request by gonpinho**
Closes #206

### CODE REVIEW

File: src/main/kotlin/com/github/imflog/schema/registry/parser/AvroSchemaParser.kt [hunk 1]
```diff
@@ -152,12 +147,15 @@ class AvroSchemaParser(
...
         references: Map<String, JSONObject>,
-        insertedReferences: MutableSet<String>,
+        insertedReferences: MutableSet<String>
     ): Any {
         val referenceKey = findReferenceKey(items, currentNamespace, references)
         if (referenceKey != null) {
-            val referencedSchema = references[referenceKey]!!
+            // deep copy the reference and resolve local references in references (as local references can have references)
+            val refSchemaCopy = JSONObject(references[referenceKey]!!.toString())
+            val referencedSchema = resolveReferences(refSchemaCopy, references, null, insertedReferences)
```
Comment (ImFlog) [inline src/main/kotlin/com/github/imflog/schema/registry/parser/AvroSchemaParser.kt:156]: Just to be sure, this means that for each run of the recursive function, if we find a reference we will re-compute the reference so that the namespace resolution is triggered with the correct namespace according to the hierarchy in place ?

Comment (gonpinho) [reply src/main/kotlin/com/github/imflog/schema/registry/parser/AvroSchemaParser.kt:156]: exactly, we make sure that we remove namespaces only on copies and not on the references map. By doing this, we make sure that we never impact other repeated references that live on different namespaces as we always keep an original copy of the local reference on the map itself
